// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxop7AszeUuuJ-KazIpgzjA4SVUIFWc9k',
    appId: '1:1035765342136:web:530899f6011fe1af2ff94d',
    messagingSenderId: '1035765342136',
    projectId: 'flutter-chat-app-a33a5',
    authDomain: 'flutter-chat-app-a33a5.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a33a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSVssTEF-X-kIzbsJqx8_d7J1egqxqQ3E',
    appId: '1:1035765342136:android:09b9c8f4a591ee9d2ff94d',
    messagingSenderId: '1035765342136',
    projectId: 'flutter-chat-app-a33a5',
    storageBucket: 'flutter-chat-app-a33a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nd-Zx1qUpDGDPl4QNrA94ASfe-0Couk',
    appId: '1:1035765342136:ios:96d4c25edc56bf642ff94d',
    messagingSenderId: '1035765342136',
    projectId: 'flutter-chat-app-a33a5',
    storageBucket: 'flutter-chat-app-a33a5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3nd-Zx1qUpDGDPl4QNrA94ASfe-0Couk',
    appId: '1:1035765342136:ios:96e256f3c3f232532ff94d',
    messagingSenderId: '1035765342136',
    projectId: 'flutter-chat-app-a33a5',
    storageBucket: 'flutter-chat-app-a33a5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
